:tddium:
  :phantomjs:
    :version: '1.8.0'
  :tests:
  - :type: custom                          # must be 'custom'
    :command: rake guard:jasmine           # Replace with whatever command you want to run
    :invocation: single                    # must be 'single'
    :output: exit-status                   # must be 'exit-status'
